[package]
name = "fastquadtree"
<<<<<<< HEAD
version = "1.3.3"
=======
version = "1.4.0"
>>>>>>> de570fd (feat: add query_np for point and rect quadtree)
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
pyo3 = { version = "0.26", features = ["extension-module", "abi3-py38"] }
smallvec = "1.15.1"
numpy = "0.26"
serde = { version = "1.0", features = ["derive"] }
bincode = {version = "2.0.1", features = ["serde"]}
num-traits = "0.2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
